// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAypmW3UpLYGtkco2Q_QWmCSd-kesO_GQ4',
    appId: '1:21244888541:web:8c75a48a1da1f91192e234',
    messagingSenderId: '21244888541',
    projectId: 'hermoine-e9367',
    authDomain: 'hermoine-e9367.firebaseapp.com',
    storageBucket: 'hermoine-e9367.appspot.com',
    measurementId: 'G-RSW5CD298M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB40sg6IK1lKmIxfVAETqbGm0SGBQlE-08',
    appId: '1:21244888541:android:baa7ac2981dff53e92e234',
    messagingSenderId: '21244888541',
    projectId: 'hermoine-e9367',
    storageBucket: 'hermoine-e9367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtrIjoGL5mo5mlZaDGiQC4hNCcaVQ3FS0',
    appId: '1:21244888541:ios:17252b10b54b0ebb92e234',
    messagingSenderId: '21244888541',
    projectId: 'hermoine-e9367',
    storageBucket: 'hermoine-e9367.appspot.com',
    iosBundleId: 'com.example.hermione',
  );
}
